---
- name: Install
  become: true
  block:
    - name: "Создание директории {{ monitoring_docker_working_directory_path }}"
      ansible.builtin.file:
        path: "{{ monitoring_docker_working_directory_path }}/monitoring"
        owner: "{{ monitoring_files_owner }}"
        group: "{{ monitoring_files_group_owner }}"
        state: directory
        mode: '0755'

    - name: Копирование docker-compose файла
      ansible.builtin.template:
        src: "docker-compose.j2"
        dest: "{{ monitoring_docker_working_directory_path }}/monitoring/docker-compose.yml"
        mode: '0644'

    - name: Запуск сервиса с помощью docker-compose
      community.docker.docker_compose_v2:
        project_src: "{{ monitoring_docker_working_directory_path }}/monitoring"
        services: "{{ monitoring_services }}"
        state: present
