---
- name: Node-exporter
  become: true
  block:
    - name: Создать директорию node-exporter
      ansible.builtin.file:
        path: "{{ monitoring_docker_working_directory_path }}/node_exporter"
        owner: devops
        group: devops
        state: directory
        mode: '0755'

    - name: Запуск контейнера
      community.docker.docker_container:
        name: node_exporter
        image: "prom/node-exporter:{{ monitoring_node_exporter_version }}"
        command: ['--path.rootfs=/host']
        network_mode: host
        pid_mode: host
        restart_policy: unless-stopped
        volumes:
          - /:/host:ro,rslave
        state: present
