services:
  loki:
    image: grafana/loki:3.5
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml
      # - ./loki_storage:/tmp/loki
      # /data/retention
    command: "-config.file=/etc/loki/config.yaml -target=all"
    restart: unless-stopped