services:
    nginx:
        image: nginx:${NGINX_VERSION}
        container_name: nginx
        volumes:
            - ${SRC_LOCAL_FOLDER}/docker/prod/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ${SRC_LOCAL_FOLDER}/docker/prod/nginx/conf.d:/etc/nginx/conf.d
            - volume_source:/var/www/project:rw
            - volume_share:/share:rw
            - ${LOGS_LOCAL_FOLDER}/nginx:/var/log/nginx:rw
            - /etc/localtime:/etc/localtime:ro
        ports:
            - '${NGINX_INTERFACE}:${NGINX_PORT}:80'
        links:
            - php
        networks:
            - mm-backend-net

    php:
        build:
            context: ../../
            dockerfile: docker/prod/php/Dockerfile
        container_name: php-backend
        volumes:
            - source:/var/www/project:rw
            - share:/share:rw
            - ${LOGS_LOCAL_FOLDER}/laravel:/var/www/project/storage/logs:rw
            - ${LOGS_LOCAL_FOLDER}/php:/var/log/php/:rw
        ports:
            - '${PHP_FPM_INTERFACE}:${PHP_FPM_PORT}:9000'
        networks:
            - mm-backend-net
        extra_hosts:
            - "host.docker.internal:host-gateway"

    redis:
        image: redis:${REDIS_VERSION}
        container_name: redis
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_USER=${REDIS_USER}
            - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
        ports:
            - "${REDIS_INTERFACE}:${REDIS_PORT}:6379"
        volumes:
            - ${SRC_LOCAL_FOLDER}/redis_data/data:/data
        command: >
            sh -c '
                mkdir -p /usr/local/etc/redis &&
                echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
                echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
                echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
                echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
                echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
                echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
                redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
            '
        healthcheck:
            test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: unless-stopped
        tty: true
        stdin_open: true
        networks:
            - mm-backend-net

volumes:
    volume_source:
        driver: local
        driver_opts:
            device: ${SRC_LOCAL_FOLDER}
            type: none
            o: bind
    volume_share:
        driver: local
        driver_opts:
            device: ${SHARE_LOCAL_FOLDER}
            type: none
            o: bind

networks:
    mm-backend-net:
        driver: bridge