services:
  kafka1-prod:
    image: confluentinc/cp-kafka:7.9.0
    container_name: kafka1-prod
    environment:
      # реплик темы, содержащей сдвиги (offsets), будет создано
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      # Уникальный идентификатор узла
      KAFKA_NODE_ID: 1
      # Уникальный идентификатор кластера (генерируется один раз)
      CLUSTER_ID: 0Ea8Ov0mSwS-YUjgXjGcHA
      # Роли узла (брокер и контроллер)
      KAFKA_PROCESS_ROLES: broker,controller

      # Используемые Протоколы
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

      # Настройка слушателей
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.50:9092,CONTROLLER://192.168.1.50:9093

      # Настройка контроллеров
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@192.168.1.50:9093,2@192.168.1.50:9095

      # Глобальная очистка всех сообщений
      KAFKA_LOG_RETENTION_MS: 87000000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
       - kafka1-data:/var/lib/kafka/data
    networks:
      - kafka-prod


  kafka2-prod:
    image: confluentinc/cp-kafka:7.9.0
    container_name: kafka2-prod
    environment:
      # реплик темы, содержащей сдвиги (offsets), будет создано
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      # Уникальный идентификатор узла
      KAFKA_NODE_ID: 2
      # Уникальный идентификатор кластера (генерируется один раз)
      CLUSTER_ID: 0Ea8Ov0mSwS-YUjgXjGcHA
      # Роли узла (брокер и контроллер)
      KAFKA_PROCESS_ROLES: broker,controller

      # Используемые Протоколы
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

      # Настройка слушателей (Локально)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094,CONTROLLER://0.0.0.0:9095
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.50:9094,CONTROLLER://192.168.1.50:9095

      # Настройка контроллеров
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@192.168.1.50:9093,2@192.168.1.50:9095

      # Глобальная очистка всех сообщений
      KAFKA_LOG_RETENTION_MS: 87000000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
    ports:
      - "9094:9094"
      - "9095:9095"
    volumes:
      - kafka2-data:/var/lib/kafka/data
    networks:
      - kafka-prod

volumes:
  kafka1-data:
    driver: local
  kafka2-data:
    driver: local

networks:
  kafka-prod:
    driver: bridge