---
- name: Converge
  hosts: all
  tasks:
    - name: Install NGINX Plus
      ansible.builtin.include_role:
        name: ansible-role-nginx
      vars:
        nginx_type: plus
        nginx_license:
          certificate: license/nginx-repo.crt
          key: license/nginx-repo.key
          jwt: license/license.jwt
        nginx_remove_license: false
        nginx_modules:
          - auth-spnego
          - brotli
          - encrypted-session
          - geoip
          - geoip2
          - headers-more
          - image-filter
          - lua
          - njs
          - opentracing
          - passenger
          - perl
          - prometheus
          - rtmp
          - set-misc
          - subs-filter
          - xslt
        nginx_keepalived_enable: true
        nginx_keepalived_conf_enable: true
        nginx_keepalived_conf:
          - virtual_router_id: 1
            primary_dev: eth0
            priority: 101
            primary_ip: 192.168.100.100
            secondary_ip:
              - 192.168.100.101
            cluster_ip:
              - 192.168.100.150
