services:
  victoria_metrics-prod:
    image: victoriametrics/victoria-metrics:v1.110.0
    container_name: victoria_metrics-prod
    ports:
      #- "127.0.0.1:8428:8428"
      - "0.0.0.0:8428:8428"
    command:
      - '--retentionPeriod=90' # Хранить данные 30 дней
      - '--memory.allowedPercent=75' # Использовать до 75% оперативной памяти
      - '--search.maxQueryDuration=30s' # Ограничение времени выполнения запросов
    volumes:
      - ./metrics_storage:/victoria-metrics-data