services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; sleep infinity & wait'"

# docker-compose run --rm certbot certonly --manual --preferred-challenges=dns --email your-email@example.com --agree-tos --no-eff-email -d moymir.tech -d '*.moymir.tech'
