services:
  nginx-ui:
    image: uozi/nginx-ui:latest
    container_name: nginx-ui
    restart: always
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./nginx_data:/etc/nginx
      - ./nginx_ui_data:/etc/nginx-ui
      - /var/www:/var/www
    ports:
      - "8080:80"
      - "8443:443"
