---
- name: (Amazon Linux/RHEL) Add NGINX Amplify agent repository
  ansible.builtin.yum_repository:
    name: nginx-amplify
    baseurl: https://packages.amplify.nginx.com/py3/{{ (ansible_facts['distribution'] == 'Amazon') | ternary('amzn', 'rhel') }}/$releasever/$basearch/
    description: NGINX Amplify Agent
    enabled: true
    gpgcheck: true
    mode: "0644"
