services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine3.19-bleeding
    container_name: gitlab-runner
    restart: always
    volumes:
      - /docker/production/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
