
services:
  debezium-connect:
    image: debezium/connect:3.0.0.Final
    container_name: debezium-connect
    environment:
      BOOTSTRAP_SERVERS: 'kafka1:9092,kafka2:9094'
      GROUP_ID: '1'
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
    ports:
      - 8083:8083
    networks:
      - kafka-net

networks:
  kafka-net:
    external: true
