---
- name: Инициализация домашней директории docker, назначения прав и владельца
  become: true
  block:
    - name: "Создание группы {{ docker_files_group_owner }}"
      ansible.builtin.group:
        name: "{{ docker_files_group_owner }}"
        state: present

    - name: Добавление пользователя в группы docker
      ansible.builtin.user:
        name: "{{ docker_files_owner }}"
        groups: "{{ docker_files_group_owner }}, docker"
        append: true
        state: present

    - name: "Создание директории {{ docker_working_directory_path }}"
      ansible.builtin.file:
        path: "{{ docker_working_directory_path }}"
        owner: "{{ docker_files_owner }}"
        group: "{{ docker_files_group_owner }}"
        state: directory
        mode: '0755'
