# ---
# - name: Site
#   hosts: ["new_site_mm-frontend-prod"]
#   gather_facts: true
#   tasks:
#     - name: Запуск роли
#       ansible.builtin.include_role:
#         name: monitoring
#         tasks_from: node_exporter.yml

#     - name: Запуск роли
#       ansible.builtin.include_role:
#         name: monitoring
#         tasks_from: cadvisor.yml

# playbook.yml
---
- name: Запуск роли
  hosts: hsr-api_server
  # gather_facts: true
  roles:
    - role: docker
      # vars:
      #   docker_service: node_exporter
      tags: Install
