---
- name: Site
  hosts: ["hsr-backend_cache"]
  gather_facts: true
  tasks:
    - name: Запуск роли
      ansible.builtin.include_role:
        name: monitoring
        tasks_from: node_exporter.yml

    #- name: Запуск роли
    #  ansible.builtin.include_role:
    #    name: monitoring
    #    tasks_from: cadvisor.yml
