---
- name: Запуск роли
  hosts: hsr-crm
  gather_facts: true
  tasks:
    - name: Запуск роли
      ansible.builtin.include_role:
        name: docker
        tasks_from: install.yml

    - name: Запуск роли
      ansible.builtin.include_role:
        name: docker
        tasks_from: init_docker_home.yml

    - name: Запуск роли
      ansible.builtin.include_role:
        name: monitoring
        tasks_from: install.yml
      vars:
        monitoring_services:
          - node_exporter
          - cadvisor
          # - alloy
