services:
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=<ipv4_address>:9092
      - KAFKA_CLUSTERS_0_NAME=kraft
      - DYNAMIC_CONFIG_ENABLED=true
    volumes:
      - ./config.yml:/etc/kafkaui/dynamic_config.yaml