services:
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - "8081:8080"
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
    volumes:
      - ./config.yml:/etc/kafkaui/dynamic_config.yaml
    networks:
      - kafka-net

networks:
  kafka-net:
    external: true