---
- name: (Alpine Linux) Configure NGINX Agent repository
  ansible.builtin.lineinfile:
    path: /etc/apk/repositories
    insertafter: EOF
    line: https://packages.nginx.org/nginx-agent/alpine/v{{ ansible_facts['distribution_version'] | regex_search('^[0-9]+\.[0-9]+') }}/main
